# Movie System Design

### 1. Load source databases

In [1]:
from pathlib import Path

DB_DIR = Path("../data")
MOVIES_DB = DB_DIR / "movies.db"
RATINGS_DB= DB_DIR / "ratings.db"

assert MOVIES_DB.exists(), f"missing {MOVIES_DB}"
assert RATINGS_DB.exists(), f"missing {RATINGS_DB}"

print(f"movies.db : {MOVIES_DB.stat().st_size/1024:.0f} KB")
print(f"ratings.db : {RATINGS_DB.stat().st_size/1024:.0f} KB")

movies.db : 28732 KB
ratings.db : 2224 KB

### 2.Sanity checks

In [2]:
import sqlite3
import pandas as pd

with sqlite3.connect(MOVIES_DB) as conn:
    movies_df = pd.read_sql("SELECT * FROM movies", conn)

print(f"Movies: {len(movies_df):,}")
print(movies_df.info())
print(movies_df.describe())
display(movies_df)

Movies: 45,430
<class 'pandas.DataFrame'>
RangeIndex: 45430 entries, 0 to 45429
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   movieId              45430 non-null  int64
 1   imdbId               45430 non-null  str
 2   title                45430 non-null  str
 3   overview             45430 non-null  str
 4   productionCompanies  45430 non-null  str
 5   releaseDate          45430 non-null  str
 6   budget               45430 non-null  int64
 7   revenue              45430 non-null  int64
 8   runtime              45430 non-null  object
 9   language             0 non-null      object
 10  genres               45430 non-null  str
 11  status               45430 non-null  str
dtypes: int64(3), object(2), str(7)
memory usage: 4.2+ MB
None
             movieId        budget       revenue
count   45430.000000  4.543000e+04  4.543000e+04
mean   108372.376535  4.224828e+06  1.121288e+07
std    112481.447389  1.742853e+07  6.435213e+07
min         2.000000  0.000000e+00  0.000000e+00
25%     26455.750000  0.000000e+00  0.000000e+00
50%     59994.000000  0.000000e+00  0.000000e+00
75%    157350.750000  0.000000e+00  0.000000e+00
max    469172.000000  3.800000e+08  2.787965e+09

,movieId,imdbId,title,overview,productionCompanies,releaseDate,budget,revenue,runtime,language,genres,status
0,2,tt0094675,Ariel,Taisto Kasurinen is a Finnish coal miner whose...,"[{""name"": ""Villealfa Filmproduction Oy"", ""id"":...",1988-10-21,0,0,69.0,None,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 80, ""name...",Released
1,3,tt0092149,Shadows in Paradise,"An episode in the life of Nikander, a garbage ...","[{""name"": ""Villealfa Filmproduction Oy"", ""id"":...",1986-10-16,0,0,76.0,None,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 35, ""name...",Released
2,5,tt0113101,Four Rooms,It's Ted the Bellhop's first night on the job....,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...",1995-12-09,4000000,4300000,98.0,None,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 35, ""name...",Released
3,6,tt0107286,Judgment Night,"While racing to a boxing match, Frank, Mike, J...","[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...",1993-10-15,0,12136938,110.0,None,"[{""id"": 28, ""name"": ""Action""}, {""id"": 53, ""nam...",Released
4,11,tt0076759,Star Wars,Princess Leia is captured and held hostage by ...,"[{""name"": ""Lucasfilm"", ""id"": 1}, {""name"": ""Twe...",1977-05-25,11000000,775398007,121.0,None,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",Released
...,...,...,...,...,...,...,...,...,...,...,...,...
45425,465044,tt5943940,Abduction,A horror comedy spoofing conspiracy theory mov...,[],2017-06-28,0,0,90.0,None,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 18, ""na...",Released
45426,467731,tt0507700,Tragedy in a Temporary Town,Fifteen-year-old girl Dotty Fisher is assaulte...,[],1956-02-19,0,0,60.0,None,"[{""id"": 18, ""name"": ""Drama""}]",Released
45427,468343,tt0133202,Silja - nuorena nukkunut,"In the 1910s, beautiful young Silja loses both...",[],1956-01-01,0,0,87.0,None,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...",Released
45428,468707,tt5742932,Thick Lashes of Lauri Mäntyvaara,,"[{""name"": ""Elokuvayhtiö Oy Aamu"", ""id"": 84883}]",2017-07-28,1254040,0,90.0,None,"[{""id"": 10749, ""name"": ""Romance""}, {""id"": 35, ...",Released
45429,469172,tt0089018,Manuel on the Island of Wonders,Manuel is a young boy who travels from long ag...,"[{""name"": ""Institut National de l""Audiovisuel ...",1984-08-02,0,0,130.0,None,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 18, ""na...",Released

In [3]:
with sqlite3.connect(RATINGS_DB) as conn:
    ratings_df = pd.read_sql("SELECT * FROM ratings", conn)

print(f"Ratings: {len(ratings_df):,}")
print(ratings_df.info())
print(ratings_df.describe())
display(ratings_df)

Ratings: 100,004
<class 'pandas.DataFrame'>
RangeIndex: 100004 entries, 0 to 100003
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   ratingId   100004 non-null  int64
 1   userId     100004 non-null  int64
 2   movieId    100004 non-null  int64
 3   rating     100004 non-null  float64
 4   timestamp  100004 non-null  int64
dtypes: float64(1), int64(4)
memory usage: 3.8 MB
None
            ratingId         userId        movieId         rating  \
count  100004.000000  100004.000000  100004.000000  100004.000000
mean    50002.500000     347.011310   12548.664363       3.543608
std     28868.812497     195.163838   26369.198969       1.058064
min         1.000000       1.000000       1.000000       0.500000
25%     25001.750000     182.000000    1028.000000       3.000000
50%     50002.500000     367.000000    2406.500000       4.000000
75%     75003.250000     520.000000    5418.000000       4.000000
max    100004.000000     671.000000  163949.000000       5.000000

          timestamp
count  1.000040e+05
mean   1.129639e+09
std    1.916858e+08
min    7.896520e+08
25%    9.658478e+08
50%    1.110422e+09
75%    1.296192e+09
max    1.476641e+09

        ratingId  userId  movieId  rating   timestamp
0              1       1       31     2.5  1260759144
1              2       1     1029     3.0  1260759179
2              3       1     1061     3.0  1260759182
3              4       1     1129     2.0  1260759185
4              5       1     1172     4.0  1260759205
...          ...     ...      ...     ...         ...
99999     100000     671     6268     2.5  1065579370
100000    100001     671     6269     4.0  1065149201
100001    100002     671     6365     4.0  1070940363
100002    100003     671     6385     2.5  1070979663
100003    100004     671     6565     3.5  1074784724

[100004 rows x 5 columns]

In [4]:
# Aggregate ratings per movie
rating_agg = (
    ratings_df.groupby("movieId")
    .agg(avg_rating=("rating", "mean"), rating_count=("rating", "count"))
    .reset_index()
)
rating_agg["avg_rating"] = rating_agg["avg_rating"].round(3)
print(f"Movies with at least 1 rating: {len(rating_agg):,}")
rating_agg.describe()

Movies with at least 1 rating: 9,066

             movieId   avg_rating  rating_count
count    9066.000000  9066.000000   9066.000000
mean    30772.100044     3.292056     11.030664
std     40418.420801     0.881967     24.050800
min         1.000000     0.500000      1.000000
25%      2829.750000     2.844000      1.000000
50%      6248.000000     3.500000      3.000000
75%     55827.500000     3.966000      9.000000
max    163949.000000     5.000000    341.000000

## 3. Sample selection

**Strategy:** stratified random sample across decades, restricted to movies with usable signal for *all* enrichments and computed columns:

- `budget > 0` and `revenue > 0` (so tiers and effectiveness score are meaningful)
- `overview` length > 50 chars (so the LLM has substantive text to reason about)
- `rating_count >= 5` (so `avg_rating` is not noise from a single user)
- valid `releaseDate`

We then take the top 6 most-represented decades and pull an equal number from each, targeting **~100 movies total**. Stratification prevents the sample from being dominated by 2000s/2010s blockbusters.

In [5]:
TARGET_SAMPLE_SIZE = 100
RANDOM_SEED = 42

movies = movies_df.copy()
movies = movies[movies["budget"] > 0]
movies = movies[movies["revenue"] > 0]
movies = movies[movies["overview"].fillna("").str.len() > 50]
movies = movies.merge(rating_agg, on="movieId", how="inner")
movies = movies[movies["rating_count"] >= 5]
movies["releaseDate"] = pd.to_datetime(movies["releaseDate"], errors="coerce")
movies = movies.dropna(subset=["releaseDate"])
movies["decade"] = (movies["releaseDate"].dt.year // 10) * 10

print(f"Movies after filtering: {len(movies):,}")
print("Per-decade availability:")
print(movies["decade"].value_counts().sort_index())

Movies after filtering: 627
Per-decade availability:
decade
1920      2
1930      6
1940     11
1950     18
1960     26
1970     36
1980     79
1990    154
2000    287
2010      8
Name: count, dtype: int64

In [6]:
top_decades = movies["decade"].value_counts().head(6).index.tolist()
n_per_decade = TARGET_SAMPLE_SIZE // len(top_decades)

sample = (
    movies[movies["decade"].isin(top_decades)]
    .groupby("decade", group_keys=False)
    .apply(lambda g: g.sample(min(n_per_decade, len(g)), random_state=RANDOM_SEED))
    .reset_index(drop=True)
)

display(sample)

,movieId,imdbId,title,overview,productionCompanies,releaseDate,budget,revenue,runtime,language,genres,status,avg_rating,rating_count
0,173,tt0046672,"20,000 Leagues Under the Sea",A ship sent to investigate a wave of mysteriou...,"[{""name"": ""Walt Disney Productions"", ""id"": 3166}]",1954-12-23,5000000,28200000,127.0,None,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 18, ""...",Released,2.564,70
1,213,tt0053125,North by Northwest,Advertising man Roger Thornhill is mistaken fo...,"[{""name"": ""Metro-Goldwyn-Mayer (MGM)"", ""id"": 8...",1959-07-07,4000000,13275000,136.0,None,"[{""id"": 9648, ""name"": ""Mystery""}, {""id"": 53, ""...",Released,4.222,9
2,521,tt0046912,Dial M for Murder,An ex-tennis pro carries out a plot to have hi...,"[{""name"": ""Warner Bros."", ""id"": 6194}]",1954-05-29,1400000,3000000,104.0,None,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 9648, ""na...",Released,3.600,10
3,346,tt0047478,Seven Samurai,A samurai answers a village's request for prot...,"[{""name"": ""Toho Company"", ""id"": 882}]",1954-04-26,2000000,271841,207.0,None,"[{""id"": 28, ""name"": ""Action""}, {""id"": 18, ""nam...",Released,3.000,6
4,261,tt0051459,Cat on a Hot Tin Roof,"Brick, an alcoholic ex-football player, drinks...","[{""name"": ""Avon Production"", ""id"": 100}, {""nam...",1958-02-17,3000000,17570324,108.0,None,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...",Released,3.716,51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,2133,tt0177971,The Perfect Storm,"In October 1991, a confluence of weather condi...","[{""name"": ""Warner Bros."", ""id"": 6194}, {""name""...",2000-03-15,120000000,325756637,130.0,None,"[{""id"": 18, ""name"": ""Drama""}]",Released,3.114,22
92,1619,tt0202677,The Way of the Gun,Parker and Longbaugh are a pair of low-level p...,[],2000-09-08,8500000,19125401,119.0,None,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",Released,3.447,19
93,4967,tt0171433,Keeping the Faith,"Best friends since they were kids, Rabbi Jacob...","[{""name"": ""Spyglass Entertainment"", ""id"": 158}...",2000-04-14,30000000,37036004,127.0,None,"[{""id"": 35, ""name"": ""Comedy""}]",Released,3.944,9
94,27,tt0411705,9 Songs,"Matt, a young glaciologist, soars across the v...","[{""name"": ""Revolution Films"", ""id"": 163}]",2004-07-16,1000000,1574623,66.0,None,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10402, ""n...",Released,3.143,7
95,2334,tt0295721,Taxi 3,A gang of thieves calling themselves the Santa...,"[{""name"": ""Europa Corp"", ""id"": 1075}]",2003-01-29,14500000,65497208,82.0,None,"[{""id"": 28, ""name"": ""Action""}, {""id"": 35, ""nam...",Released,3.344,16

In [7]:
# genres and production companies in movies.db are stored as JSON lists, we can parse them to extract names
import json

def _parse_json_list(s):
    try:
        items = json.loads(s) if isinstance(s, str) else []
        return "|".join(x.get("name", "") for x in items if x.get("name"))
    except Exception:
        return ""

sample = sample.copy()
sample["genres_clean"] = sample["genres"].apply(_parse_json_list)
sample["companies_clean"] = sample["productionCompanies"].apply(_parse_json_list)
sample[["title", "genres_clean", "companies_clean"]].head()

,title,genres_clean,companies_clean
0,"20,000 Leagues Under the Sea",Adventure|Drama|Science Fiction,Walt Disney Productions
1,North by Northwest,Mystery|Thriller,Metro-Goldwyn-Mayer (MGM)
2,Dial M for Murder,Crime|Mystery|Thriller,Warner Bros.
3,Seven Samurai,Action|Drama,Toho Company
4,Cat on a Hot Tin Roof,Drama|Romance,Avon Production|Metro-Goldwyn-Mayer (MGM)

In [8]:
from typing import List
from enum import Enum
from pydantic import BaseModel, Field

class Sentiment(str, Enum):
    POSITIVE = "positive"
    NEGATIVE = "negative"
    NEUTRAL = "neutral"

class TargetAudience(str, Enum):
    CHILDREN = "children"
    FAMILY = "family"
    TEENS = "teens"
    YOUNG_ADULTS = "young_adults"
    ADULTS = "adults"
    MATURE = "mature"

class Tone(str, Enum):
    DARK = "dark"
    LIGHTHEARTED = "lighthearted"
    SERIOUS = "serious"
    HUMOROUS = "humorous"
    SUSPENSEFUL = "suspenseful"
    ROMANTIC = "romantic"
    MELANCHOLIC = "melancholic"
    INSPIRATIONAL = "inspirational"
    SATIRICAL = "satirical"

class MovieEnrichment(BaseModel):
    """Structured enrichment for a single movie."""
    sentiment: Sentiment = Field(..., description="Emotional tone the overview evokes")
    target_audience: TargetAudience = Field(..., description="Most likely primary audience")
    tone: Tone = Field(..., description="Dominant tone of the film")
    themes: List[str] = Field(
        ...,
        description="2-4 thematic tags (lowercase short noun phrases, e.g. 'redemption')",
        min_length=2, max_length=4,
    )
    sub_genre: str = Field(..., description="Specific sub-genre, lowercase (e.g. 'neo-noir')")

# Schema used in the prompt-engineering demo below
class SentimentOnly(BaseModel):
    sentiment: Sentiment

In [9]:
!uv add langchain_anthropic

warning: `VIRTUAL_ENV=/Users/sreedevidodla/Documents/Satish/AI Projects/MovieAI/venv` does not match the project environment path `/Users/sreedevidodla/Documents/Satish/AI Projects/MovieAI/.venv` and will be ignored; use `--active` to target the active environment instead
Resolved 34 packages in 13ms
Audited 33 packages in 6ms

In [10]:
import os
from langchain_anthropic import ChatAnthropic
from langchain_core.prompts import ChatPromptTemplate

anthropic_api_key = os.getenv("ANTHROPIC_API_KEY")
print("ANTHROPIC_API_KEY ->", anthropic_api_key)

MODEL_NAME = "claude-sonnet-4-20250514"

llm = ChatAnthropic(
    model=MODEL_NAME,
    temperature=0,
)
print(f"Initialized {MODEL_NAME}")

ANTHROPIC_API_KEY -> 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
Initialized claude-sonnet-4-20250514

## 4. Data Preparation & data enrichment prompt (all 5 additional attributes as specified in the problem definition)

Doing all 5 attributes in a single call is roughly 5x cheaper and faster than 5 separate calls, and lets the model reason holistically — a movie's `tone` and `target_audience` are correlated, so joint inference is sensible

In [11]:
PROMPT_VERSION = "v1-unified"

ENRICHMENT_SYSTEM = """You are a film analyst producing structured metadata enrichments.

For each movie, return 5 attributes following these rules:

1. SENTIMENT — emotional tone the overview tries to evoke (NOT whether plot events are good/bad).
   - positive: heartwarming, hopeful, uplifting framing
   - negative: bleak, despairing, hopeless framing
   - neutral: pure plot description, or balanced framing

2. TARGET_AUDIENCE — most likely PRIMARY audience.
   - children (under 10) | family (all ages together) | teens (13-17)
   - young_adults (18-25) | adults (25+) | mature (explicit/restricted)

3. TONE — the dominant tone of the film. Pick the single best fit from the allowed set.

4. THEMES — 2 to 4 thematic concepts as short lowercase noun phrases.
   Good examples: "redemption", "class struggle", "loss of innocence", "found family"
   Bad examples: "the movie is about love", "people doing things"

5. SUB_GENRE — a specific sub-genre more granular than the broad genre tags.
   Good examples: "neo-noir", "coming-of-age drama", "space opera", "slasher horror"
   Use lowercase. Be specific but conventional — prefer recognized sub-genre names.

Be decisive. If genuinely uncertain between two labels, pick the closer fit and move on."""

enrich_prompt = ChatPromptTemplate.from_messages([
    ("system", ENRICHMENT_SYSTEM),
    ("user", "Title: {title}\nGenres: {genres}\n\nOverview: {overview}"),
])

enrich_chain = enrich_prompt | llm.with_structured_output(MovieEnrichment)

In [12]:
# Enrichment on full sample. loop with progress and error handling
def enrich_one(title: str, genres: str, overview: str) -> MovieEnrichment:
    return enrich_chain.invoke({"title": title, "genres": genres, "overview": overview})

enrichments = []
failures = []
total = len(sample)
print_every = max(1, total // 10)  # ~10 progress updates over the run

for i, (_, row) in enumerate(sample.iterrows(), start=1):
    try:
        result = enrich_one(row["title"], row["genres_clean"], row["overview"])
        enrichments.append({
            "movieId": row["movieId"],
            "sentiment": result.sentiment.value,
            "target_audience": result.target_audience.value,
            "tone": result.tone.value,
            "themes": "|".join(result.themes),
            "sub_genre": result.sub_genre.lower().strip(),
        })
    except Exception as e:
        failures.append({"movieId": row["movieId"], "title": row["title"], "error": str(e)})

    if i % print_every == 0 or i == total:
        print(f"Enriching: {i}/{total} ({i/total:.0%})")

print(f"\nSucceeded: {len(enrichments)} / {len(sample)}")
print(f"Failed: {len(failures)}")
if failures:
    print("\nFailures:")
    for f in failures:
        print(f"  - {f['title']} (movieId={f['movieId']}): {f['error'][:100]}")

enrich_df = pd.DataFrame(enrichments)
enrich_df.head()

Enriching: 9/96 (9%)
Enriching: 18/96 (19%)
Enriching: 27/96 (28%)
Enriching: 36/96 (38%)
Enriching: 45/96 (47%)
Enriching: 54/96 (56%)
Enriching: 63/96 (66%)
Enriching: 72/96 (75%)
Enriching: 81/96 (84%)
Enriching: 90/96 (94%)
Enriching: 96/96 (100%)

Succeeded: 96 / 96
Failed: 0

,movieId,sentiment,target_audience,tone,themes,sub_genre
0,173,neutral,family,suspenseful,exploration|technology|mystery|isolation,underwater adventure
1,213,positive,adults,suspenseful,mistaken identity|chase|espionage,spy thriller
2,521,neutral,adults,suspenseful,betrayal|deception|marital discord|moral corru...,psychological thriller
3,346,positive,adults,serious,honor|sacrifice|community defense|warrior code,samurai epic
4,261,negative,adults,serious,family dysfunction|mortality|repressed sexuali...,family drama

## 5. Computed columns

### Tiers (absolute thresholds, industry-conventional)

| Tier   | Budget       | Revenue        |
|--------|--------------|----------------|
| low    | < \$10M      | < \$50M        |
| medium | \$10M – \$50M | \$50M – \$200M  |
| high   | ≥ \$50M      | ≥ \$200M       |

### Production Effectiveness Score

We combine **commercial success (ROI)** and **critical reception (avg user rating)** into a 0–1 score:

```
roi          = revenue / budget
roi_score    = clip(log10(roi) / 2, 0, 1)        # break-even -> 0, 100x -> 1
rating_score = (avg_rating - 0.5) / 4.5          # 0.5 -> 0, 5.0 -> 1
score        = 0.5 * roi_score + 0.5 * rating_score
```

In [13]:
import numpy as np

def budget_tier(b):
    if b < 10_000_000: return "low"
    if b < 50_000_000: return "medium"
    return "high"

def revenue_tier(r):
    if r < 50_000_000: return "low"
    if r < 200_000_000: return "medium"
    return "high"

def effectiveness_score(row):
    if row["budget"] <= 0:
        return None
    roi = row["revenue"] / row["budget"]
    roi_score = float(np.clip(np.log10(roi + 1e-3) / 2, 0, 1))
    rating_score = float((row["avg_rating"] - 0.5) / 4.5)
    return round(0.5 * roi_score + 0.5 * rating_score, 3)

sample_computed = sample.copy()
sample_computed["budget_tier"] = sample_computed["budget"].apply(budget_tier)
sample_computed["revenue_tier"] = sample_computed["revenue"].apply(revenue_tier)
sample_computed["production_effectiveness_score"] = sample_computed.apply(effectiveness_score, axis=1)

sample_computed[[
    "title", "budget", "revenue", "avg_rating",
    "budget_tier", "revenue_tier", "production_effectiveness_score",
]].head(10)

,title,budget,revenue,avg_rating,budget_tier,revenue_tier,production_effectiveness_score
0,"20,000 Leagues Under the Sea",5000000,28200000,2.564,low,low,0.417
1,North by Northwest,4000000,13275000,4.222,low,low,0.544
2,Dial M for Murder,1400000,3000000,3.600,low,low,0.427
3,Seven Samurai,2000000,271841,3.000,low,low,0.278
4,Cat on a Hot Tin Roof,3000000,17570324,3.716,low,low,0.549
5,Roman Holiday,1500000,12000000,2.893,low,low,0.492
6,An American in Paris,2723903,4500000,2.333,low,low,0.258
7,Touch of Evil,829000,2247465,3.583,low,low,0.451
8,Sunset Boulevard,1752000,5000000,4.036,low,low,0.507
9,Some Like It Hot,2883848,25000000,2.933,low,low,0.505

In [14]:
# Merge everything together for final output
final_df = sample_computed.merge(enrich_df, on="movieId", how="inner")

output_cols = [
    # identity & source
    "movieId", "imdbId", "title", "overview", "releaseDate",
    "budget", "revenue", "runtime", "language",
    "genres_clean", "companies_clean",
    "avg_rating", "rating_count",
    # LLM-derived
    "sentiment", "target_audience", "tone", "themes", "sub_genre",
    # Computed
    "budget_tier", "revenue_tier", "production_effectiveness_score",
]
final_df = final_df[output_cols].rename(columns={
    "genres_clean": "genres",
    "companies_clean": "production_companies",
})
final_df["releaseDate"] = final_df["releaseDate"].astype(str)

print(f"Final shape: {final_df.shape}")
final_df.head()

Final shape: (96, 21)

,movieId,imdbId,title,overview,releaseDate,budget,revenue,runtime,language,genres,...,avg_rating,rating_count,sentiment,target_audience,tone,themes,sub_genre,budget_tier,revenue_tier,production_effectiveness_score
0,173,tt0046672,"20,000 Leagues Under the Sea",A ship sent to investigate a wave of mysteriou...,1954-12-23,5000000,28200000,127.0,None,Adventure|Drama|Science Fiction,...,2.564,70,neutral,family,suspenseful,exploration|technology|mystery|isolation,underwater adventure,low,low,0.417
1,213,tt0053125,North by Northwest,Advertising man Roger Thornhill is mistaken fo...,1959-07-07,4000000,13275000,136.0,None,Mystery|Thriller,...,4.222,9,positive,adults,suspenseful,mistaken identity|chase|espionage,spy thriller,low,low,0.544
2,521,tt0046912,Dial M for Murder,An ex-tennis pro carries out a plot to have hi...,1954-05-29,1400000,3000000,104.0,None,Crime|Mystery|Thriller,...,3.600,10,neutral,adults,suspenseful,betrayal|deception|marital discord|moral corru...,psychological thriller,low,low,0.427
3,346,tt0047478,Seven Samurai,A samurai answers a village's request for prot...,1954-04-26,2000000,271841,207.0,None,Action|Drama,...,3.000,6,positive,adults,serious,honor|sacrifice|community defense|warrior code,samurai epic,low,low,0.278
4,261,tt0051459,Cat on a Hot Tin Roof,"Brick, an alcoholic ex-football player, drinks...",1958-02-17,3000000,17570324,108.0,None,Drama|Romance,...,3.716,51,negative,adults,serious,family dysfunction|mortality|repressed sexuali...,family drama,low,low,0.549

In [15]:
from datetime import datetime, timezone

OUTPUT_DB = "../data/output/enriched_movies.db"

with sqlite3.connect(OUTPUT_DB) as conn:
    final_df.to_sql("enriched_movies", conn, if_exists="replace", index=False)

    metadata = pd.DataFrame([{
        "model_name": MODEL_NAME,
        "prompt_version": PROMPT_VERSION,
        "run_date_utc": datetime.now(timezone.utc).isoformat(),
        "sample_size": len(final_df),
        "llm_attributes": "sentiment,target_audience,tone,themes,sub_genre",
        "computed_attributes": "budget_tier,revenue_tier,production_effectiveness_score",
        "framework": "langchain + langchain-google-genai + pandas",
        "random_seed": RANDOM_SEED,
    }])
    metadata.to_sql("enrichment_metadata", conn, if_exists="replace", index=False)

print(f"Wrote {len(final_df)} rows to {OUTPUT_DB}")

Wrote 96 rows to ../data/output/enriched_movies.db

# Validate

In [16]:
with sqlite3.connect(OUTPUT_DB) as conn:
    print("Tables in enriched_movies.db:")
    print(pd.read_sql("SELECT name FROM sqlite_master WHERE type='table'", conn))

    print("\nMetadata:")
    print(pd.read_sql("SELECT * FROM enrichment_metadata", conn).T)

    print("\nFirst 10 enriched rows (key columns):")
    print(pd.read_sql("""
        SELECT title, sentiment, target_audience, tone, sub_genre,
               budget_tier, revenue_tier, production_effectiveness_score
        FROM enriched_movies LIMIT 10
    """, conn).to_string(index=False))

Tables in enriched_movies.db:
                  name
0      enriched_movies
1  enrichment_metadata

Metadata:
                                                                     0
model_name                                    claude-sonnet-4-20250514
prompt_version                                              v1-unified
run_date_utc                          2026-04-28T16:52:36.989217+00:00
sample_size                                                         96
llm_attributes         sentiment,target_audience,tone,themes,sub_genre
computed_attributes  budget_tier,revenue_tier,production_effectiven...
framework                  langchain + langchain-google-genai + pandas
random_seed                                                         42

First 10 enriched rows (key columns):
                       title sentiment target_audience         tone              sub_genre budget_tier revenue_tier  production_effectiveness_score
20,000 Leagues Under the Sea   neutral          family  suspenseful   underwater adventure         low          low                           0.417
          North by Northwest  positive          adults  suspenseful           spy thriller         low          low                           0.544
           Dial M for Murder   neutral          adults  suspenseful psychological thriller         low          low                           0.427
               Seven Samurai  positive          adults      serious           samurai epic         low          low                           0.278
       Cat on a Hot Tin Roof  negative          adults      serious           family drama         low          low                           0.549
               Roman Holiday  positive          adults     romantic        romantic comedy         low          low                           0.492
        An American in Paris  positive          adults lighthearted        musical romance         low          low                           0.258
               Touch of Evil  negative          adults         dark               neo-noir         low          low                           0.451
            Sunset Boulevard  negative          adults         dark         hollywood noir         low          low                           0.507
            Some Like It Hot  positive          adults     humorous       screwball comedy         low          low                           0.505

In [17]:
with sqlite3.connect(OUTPUT_DB) as conn:
    print("--- Sentiment distribution ---")
    print(pd.read_sql("SELECT sentiment, COUNT(*) AS n FROM enriched_movies GROUP BY sentiment ORDER BY n DESC", conn).to_string(index=False))

    print("\n--- Target audience ---")
    print(pd.read_sql("SELECT target_audience, COUNT(*) AS n FROM enriched_movies GROUP BY target_audience ORDER BY n DESC", conn).to_string(index=False))

    print("\n--- Tone ---")
    print(pd.read_sql("SELECT tone, COUNT(*) AS n FROM enriched_movies GROUP BY tone ORDER BY n DESC", conn).to_string(index=False))

    print("\n--- Top 10 sub-genres ---")
    print(pd.read_sql("SELECT sub_genre, COUNT(*) AS n FROM enriched_movies GROUP BY sub_genre ORDER BY n DESC LIMIT 10", conn).to_string(index=False))

    print("\n--- Avg effectiveness score by budget tier ---")
    print(pd.read_sql("SELECT budget_tier, ROUND(AVG(production_effectiveness_score), 3) AS avg_score, COUNT(*) AS n FROM enriched_movies GROUP BY budget_tier", conn).to_string(index=False))

--- Sentiment distribution ---
sentiment  n
 positive 37
  neutral 33
 negative 26

--- Target audience ---
target_audience  n
         adults 72
         family 11
         mature 10
          teens  3

--- Tone ---
         tone  n
  suspenseful 26
         dark 20
      serious 15
 lighthearted 14
inspirational  7
     humorous  6
     romantic  4
  melancholic  4

--- Top 10 sub-genres ---
             sub_genre  n
          spy thriller  5
psychological thriller  5
      screwball comedy  4
           space opera  3
       romantic comedy  3
   psychological drama  3
              neo-noir  3
         zombie horror  2
  psychological horror  2
      dystopian sci-fi  2

--- Avg effectiveness score by budget tier ---
budget_tier  avg_score  n
       high      0.407 11
        low      0.491 50
     medium      0.474 35

# Movie System Design

In [20]:
from anthropic import Anthropic


_client = None  # lazy init

def _get_client():
    global _client
    if not isinstance(_client, Anthropic):
        _client = Anthropic()  # picks up ANTHROPIC_API_KEY from env
    return _client

def call_llm(user_prompt: str,
             system: str | None = None,
             model: str = MODEL_NAME,
             max_tokens: int = 1024,
             temperature: float = 0.0,
             prefill: str | None = None) -> str:
    """Single-turn call. If prefill is given, it's prepended to the response."""
    messages = [{"role": "user", "content": user_prompt}]
    if prefill is not None:
        messages.append({"role": "assistant", "content": prefill})

    kwargs = dict(model=model, max_tokens=max_tokens,
                  temperature=temperature, messages=messages)
    if system:
        kwargs["system"] = system

    resp = _get_client().messages.create(**kwargs)
    text = "".join(b.text for b in resp.content if getattr(b, "type", None) == "text")
    # The API doesn't echo the prefill back; prepend it so the caller gets a complete response
    return (prefill + text) if prefill else text

# Quick smoke test (uncomment to verify your key works):
print(call_llm("Say 'ok' and nothing else.", max_tokens=10))

/var/folders/m8/30j490cd23vdfw3yn93z97tm0000gn/T/ipykernel_37720/2853460120.py:28: DeprecationWarning: The model 'claude-sonnet-4-20250514' is deprecated and will reach end-of-life on June 15th, 2026.
Please migrate to a newer model. Visit https://docs.anthropic.com/en/docs/resources/model-deprecations for more information.
  resp = _get_client().messages.create(**kwargs)

ok

In [21]:
# Build the schema string we'll inject into the system prompt
schema_lines = []
for _, row in pd.read_sql("PRAGMA table_info(enriched_movies);", conn).iterrows():
    schema_lines.append(f"  {row['name']} {row['type']}")
SCHEMA_STR = "TABLE enriched_movies (\n" + "\n".join(schema_lines) + "\n)"

# Few-shot examples — picked to cover: simple filter, aggregation, multi-condition with LIKE
FEWSHOT_NL2SQL = [
    ("How many movies in each sentiment bucket?",
     "SELECT sentiment, COUNT(*) AS n FROM enriched_movies GROUP BY sentiment ORDER BY n DESC;"),
    ("Top 5 highest-rated movies with at least 50 ratings",
     "SELECT title, avg_rating, rating_count FROM enriched_movies WHERE rating_count >= 50 ORDER BY avg_rating DESC LIMIT 5;"),
    ("Find suspenseful action thrillers aimed at adults",
     "SELECT title, genres, tone, target_audience FROM enriched_movies WHERE genres LIKE '%Action%' AND genres LIKE '%Thriller%' AND tone = 'suspenseful' AND target_audience = 'adults' LIMIT 50;"),
]

NL2SQL_SYSTEM = f"""You are a SQL generator for a movies SQLite database.

{SCHEMA_STR}

Notes:
- `genres` is a pipe-separated string (e.g. 'Action|Adventure|Fantasy'); use LIKE '%Genre%' to filter.
- `themes` is also pipe-separated.
- `sentiment` ∈ {{'positive','negative','neutral'}}.
- `budget_tier` and `revenue_tier` ∈ {{'low','medium','high'}}.
- `target_audience` ∈ {{'family','teens','adults','mature'}}.
- `tone` examples: 'suspenseful','serious','dark','lighthearted','romantic','humorous','inspirational'.

Rules:
- Output ONE SQL statement only. No prose, no markdown fences, no explanations.
- Read-only: use SELECT only. Never use INSERT/UPDATE/DELETE/DROP/ALTER.
- Always include LIMIT 50 unless the query is an aggregation.
"""

# Build the user-message body that combines few-shot + the new question
def build_nl2sql_prompt(question: str) -> str:
    parts = []
    for q, sql in FEWSHOT_NL2SQL:
        parts.append(f"Question: {q}\nSQL: {sql}")
    parts.append(f"Question: {question}\nSQL:")
    return "\n\n".join(parts)

print(NL2SQL_SYSTEM[:500] + "\n...")
print("\n--- example user prompt ---")
print(build_nl2sql_prompt("Recommend action movies with high revenue and positive sentiment"))

You are a SQL generator for a movies SQLite database.

TABLE enriched_movies (
  movieId INTEGER
  imdbId TEXT
  title TEXT
  overview TEXT
  releaseDate TEXT
  budget INTEGER
  revenue INTEGER
  runtime REAL
  language TEXT
  genres TEXT
  production_companies TEXT
  avg_rating REAL
  rating_count INTEGER
  sentiment TEXT
  target_audience TEXT
  tone TEXT
  themes TEXT
  sub_genre TEXT
  budget_tier TEXT
  revenue_tier TEXT
  production_effectiveness_score REAL
)

Notes:
- `genres` is a pipe-s
...

--- example user prompt ---
Question: How many movies in each sentiment bucket?
SQL: SELECT sentiment, COUNT(*) AS n FROM enriched_movies GROUP BY sentiment ORDER BY n DESC;

Question: Top 5 highest-rated movies with at least 50 ratings
SQL: SELECT title, avg_rating, rating_count FROM enriched_movies WHERE rating_count >= 50 ORDER BY avg_rating DESC LIMIT 5;

Question: Find suspenseful action thrillers aimed at adults
SQL: SELECT title, genres, tone, target_audience FROM enriched_movies WHERE genres LIKE '%Action%' AND genres LIKE '%Thriller%' AND tone = 'suspenseful' AND target_audience = 'adults' LIMIT 50;

Question: Recommend action movies with high revenue and positive sentiment
SQL:

In [22]:
import re, textwrap, random

# Safety-guard + executor for generated SQL
SAFE_PREFIX = re.compile(r"^\s*select\b", re.IGNORECASE)
FORBIDDEN   = re.compile(r"\b(insert|update|delete|drop|alter|attach|pragma|create|replace)\b", re.IGNORECASE)

def safe_run_sql(sql: str, conn=conn) -> pd.DataFrame:
    sql = sql.strip().rstrip(";").strip()
    if not SAFE_PREFIX.match(sql):
        raise ValueError(f"Refusing non-SELECT SQL: {sql[:80]}...")
    if FORBIDDEN.search(sql):
        raise ValueError(f"Refusing SQL containing forbidden keyword: {sql[:80]}...")
    if " limit " not in sql.lower() and " group by " not in sql.lower():
        sql += " LIMIT 50"
    return pd.read_sql(sql, conn)

# Sanity-check the guard with a hand-written SELECT (no LLM needed for this)
demo = safe_run_sql("SELECT title, revenue, sentiment FROM enriched_movies WHERE genres LIKE '%Action%' AND sentiment='positive' ORDER BY revenue DESC LIMIT 5")
print(demo.to_string(index=False))

                             title   revenue sentiment
                         Star Wars 775398007  positive
Indiana Jones and the Last Crusade 474171806  positive
                 National Treasure 347451894  positive
      Teenage Mutant Ninja Turtles 202000000  positive
                           Ben-Hur 146900000  positive

In [23]:
# Live LLM round-trip: question -> SQL -> DataFrame
TEST_QUESTIONS = [
    "Recommend action movies with high revenue and positive sentiment",
    "Which family-audience movies have the highest production_effectiveness_score?",
    "List dark-toned dramas released before 1970, with their average rating",
]

for q in TEST_QUESTIONS:
    print("=" * 70)
    print("Q:", q)
    sql = call_llm(build_nl2sql_prompt(q), system=NL2SQL_SYSTEM, max_tokens=300).strip()
    print("SQL:", sql)
    try:
        result = safe_run_sql(sql)
        print(result.to_string(index=False) if len(result) else "(no rows)")
    except Exception as e:
        print("ERROR:", e)

======================================================================
Q: Recommend action movies with high revenue and positive sentiment

/var/folders/m8/30j490cd23vdfw3yn93z97tm0000gn/T/ipykernel_37720/2853460120.py:28: DeprecationWarning: The model 'claude-sonnet-4-20250514' is deprecated and will reach end-of-life on June 15th, 2026.
Please migrate to a newer model. Visit https://docs.anthropic.com/en/docs/resources/model-deprecations for more information.
  resp = _get_client().messages.create(**kwargs)

SQL: SELECT title, avg_rating, revenue, sentiment FROM enriched_movies WHERE genres LIKE '%Action%' AND revenue_tier = 'high' AND sentiment = 'positive' ORDER BY avg_rating DESC LIMIT 50;
                             title  avg_rating   revenue sentiment
                         Star Wars       3.689 775398007  positive
Indiana Jones and the Last Crusade       3.441 474171806  positive
                 National Treasure       3.222 347451894  positive
      Teenage Mutant Ninja Turtles       3.000 202000000  positive
======================================================================
Q: Which family-audience movies have the highest production_effectiveness_score?

/var/folders/m8/30j490cd23vdfw3yn93z97tm0000gn/T/ipykernel_37720/2853460120.py:28: DeprecationWarning: The model 'claude-sonnet-4-20250514' is deprecated and will reach end-of-life on June 15th, 2026.
Please migrate to a newer model. Visit https://docs.anthropic.com/en/docs/resources/model-deprecations for more information.
  resp = _get_client().messages.create(**kwargs)

SQL: SELECT title, production_effectiveness_score, genres FROM enriched_movies WHERE target_audience = 'family' ORDER BY production_effectiveness_score DESC LIMIT 50;
                             title  production_effectiveness_score                                                 genres
                         Star Wars                           0.816                       Adventure|Action|Science Fiction
Indiana Jones and the Last Crusade                           0.575                                       Adventure|Action
      Teenage Mutant Ninja Turtles                           0.572         Science Fiction|Action|Adventure|Comedy|Family
                      Mary Poppins                           0.570                                  Comedy|Family|Fantasy
                            Taxi 3                           0.480                                          Action|Comedy
                              Hook                           0.469                        Adventure|Fantasy|Comedy|Family
                 National Treasure                           0.438                      Adventure|Action|Thriller|Mystery
      20,000 Leagues Under the Sea                           0.417                        Adventure|Drama|Science Fiction
                  Fantastic Voyage                           0.404                              Adventure|Science Fiction
             Pocketful of Miracles                           0.354                                           Comedy|Drama
  Teenage Mutant Ninja Turtles III                           0.244 Action|Adventure|Comedy|Family|Fantasy|Science Fiction
======================================================================
Q: List dark-toned dramas released before 1970, with their average rating

/var/folders/m8/30j490cd23vdfw3yn93z97tm0000gn/T/ipykernel_37720/2853460120.py:28: DeprecationWarning: The model 'claude-sonnet-4-20250514' is deprecated and will reach end-of-life on June 15th, 2026.
Please migrate to a newer model. Visit https://docs.anthropic.com/en/docs/resources/model-deprecations for more information.
  resp = _get_client().messages.create(**kwargs)

SQL: SELECT title, releaseDate, avg_rating FROM enriched_movies WHERE genres LIKE '%Drama%' AND tone = 'dark' AND releaseDate < '1970-01-01' ORDER BY avg_rating DESC LIMIT 50;
               title releaseDate  avg_rating
    Sunset Boulevard  1950-08-10       4.036
The Bride Wore Black  1968-03-22       3.667
       Touch of Evil  1958-04-23       3.583
              Lolita  1962-06-13       3.326

In [24]:
# Synthetic users, anchored to real DB titles
USERS = {
    "u1_classic_drama": {
        "description": "Classic-era drama enthusiast; fond of dark and serious tones",
        "ratings": [
            ("Sunset Boulevard", 5.0),
            ("Touch of Evil", 4.5),
            ("Cat on a Hot Tin Roof", 4.0),
            ("North by Northwest", 4.5),
            ("The Shawshank Redemption", 4.5),
        ],
    },
    "u2_popcorn_action": {
        "description": "Mainstream action/adventure viewer; family-friendly leanings",
        "ratings": [
            ("Spider-Man 2", 4.5),
            ("Indiana Jones and the Last Crusade", 5.0),
            ("Mary Poppins", 3.0),
            ("The Bourne Supremacy", 4.0),
            ("Bullitt", 3.5),
        ],
    },
    "u3_indie_quirky": {
        "description": "Indie/arthouse leaner with a soft spot for romance",
        "ratings": [
            ("Amélie", 5.0),
            ("Some Like It Hot", 4.0),
            ("Sunset Boulevard", 4.0),
        ],
    },
}

# Verify every titled movie is actually in the DB (so recs are checkable)
for uid, u in USERS.items():
    for title, _ in u["ratings"]:
        n = pd.read_sql("SELECT COUNT(*) AS n FROM enriched_movies WHERE title = ?", conn, params=[title]).iloc[0, 0]
        assert n == 1, f"Title not unique/found in DB: {title!r}"
print("All synthetic users reference real DB movies. ✓")

All synthetic users reference real DB movies. ✓

In [25]:
# Build the candidate pool (everything the user hasn't already rated) and
# pass it to the LLM as compact rows. Keeping rows short keeps token cost down.
def candidate_pool(user_titles, max_rows=60):
    placeholders = ",".join("?" * len(user_titles))
    df = pd.read_sql(
        f"""SELECT title, genres, sub_genre, tone, sentiment, target_audience, avg_rating
            FROM enriched_movies
            WHERE title NOT IN ({placeholders})
              AND avg_rating IS NOT NULL
            ORDER BY rating_count DESC
            LIMIT {max_rows}""",
        conn, params=list(user_titles))
    return df

uid = "u1_classic_drama"
pool = candidate_pool([t for t, _ in USERS[uid]["ratings"]])
print(f"Pool size for {uid}: {len(pool)}")
print(pool.head(8).to_string(index=False))

Pool size for u1_classic_drama: 60
                title                            genres              sub_genre        tone sentiment target_audience  avg_rating
     The Conversation               Crime|Drama|Mystery psychological thriller suspenseful  negative          adults       3.398
To Kill a Mockingbird                       Crime|Drama        courtroom drama     serious  positive          adults       3.750
               Psycho             Drama|Horror|Thriller psychological thriller suspenseful  negative          adults       3.428
     Live and Let Die         Adventure|Action|Thriller           spy thriller suspenseful   neutral          adults       3.396
     Dawn of the Dead             Fantasy|Horror|Action          zombie horror        dark  negative          mature       3.886
            High Noon                           Western  psychological western suspenseful   neutral          adults       3.336
 The Bourne Supremacy             Action|Drama|Thriller           spy thriller suspenseful   neutral          adults       3.915
2001: A Space Odyssey Science Fiction|Mystery|Adventure   philosophical sci-fi     serious   neutral          adults       3.690

In [26]:
import json

# Recommendation prompt: structured JSON output + reasoning fields
REC_SYSTEM = textwrap.dedent("""\
    You are a movie recommendation engine. Given a user's rating history and a
    candidate pool of movies, recommend exactly 5 movies the user is most
    likely to enjoy.

    Output strict JSON in this schema, with no prose before or after:
    {
      "user_taste_profile": "<2-3 sentence summary of the user's taste>",
      "recommendations": [
        {
          "title": "<exact title from candidate pool>",
          "predicted_rating": <float, 0.5..5.0>,
          "reason": "<one sentence tying back to specific movies they rated>"
        },
        ...exactly 5 items...
      ]
    }
""")

def format_user_block(uid: str) -> str:
    u = USERS[uid]
    lines = [f"User: {uid}", f"Description: {u['description']}", "Rated:"]
    for t, r in u["ratings"]:
        meta = pd.read_sql("SELECT genres, sub_genre, tone, sentiment FROM enriched_movies WHERE title = ?", conn, params=[t]).iloc[0]
        lines.append(f"  - {t}  rating={r}  [{meta['genres']} | {meta['sub_genre']} | {meta['tone']} | {meta['sentiment']}]")
    return "\n".join(lines)

def format_pool_block(df: pd.DataFrame) -> str:
    rows = ["Candidate pool:"]
    for _, r in df.iterrows():
        rows.append(f"  - {r['title']} | {r['genres']} | {r['sub_genre']} | {r['tone']} | {r['sentiment']} | aud={r['target_audience']} | avg={r['avg_rating']}")
    return "\n".join(rows)

uid = "u1_classic_drama"
pool = candidate_pool([t for t, _ in USERS[uid]["ratings"]])
prompt = format_user_block(uid) + "\n\n" + format_pool_block(pool)
raw = call_llm(prompt, system=REC_SYSTEM, max_tokens=900, prefill="{")
print(raw)
parsed = json.loads(raw)
print("\nParsed recommendations:")
for rec in parsed["recommendations"]:
    print(f"  • {rec['title']:<35} predicted={rec['predicted_rating']}  — {rec['reason']}")

/var/folders/m8/30j490cd23vdfw3yn93z97tm0000gn/T/ipykernel_37720/2853460120.py:28: DeprecationWarning: The model 'claude-sonnet-4-20250514' is deprecated and will reach end-of-life on June 15th, 2026.
Please migrate to a newer model. Visit https://docs.anthropic.com/en/docs/resources/model-deprecations for more information.
  resp = _get_client().messages.create(**kwargs)

{
  "user_taste_profile": "This user gravitates toward classic-era dramas with dark, serious tones and sophisticated storytelling. They appreciate both noir aesthetics and psychological complexity, showing strong preference for films that blend drama with crime, thriller, or mystery elements.",
  "recommendations": [
    {
      "title": "The Conversation",
      "predicted_rating": 4.3,
      "reason": "This psychological thriller shares the dark, suspenseful qualities of Touch of Evil and the serious dramatic weight of Sunset Boulevard."
    },
    {
      "title": "Psycho",
      "predicted_rating": 4.2,
      "reason": "The psychological thriller elements and dark tone align perfectly with their love for Touch of Evil and Sunset Boulevard's noir sensibilities."
    },
    {
      "title": "To Kill a Mockingbird",
      "predicted_rating": 4.1,
      "reason": "This serious courtroom drama matches their appreciation for weighty dramatic material like Cat on a Hot Tin Roof and The Shawshank Redemption."
    },
    {
      "title": "Casino",
      "predicted_rating": 4.0,
      "reason": "The dark crime epic tone resonates with their high ratings for Touch of Evil and The Shawshank Redemption's criminal underworld elements."
    },
    {
      "title": "Rosemary's Baby",
      "predicted_rating": 3.9,
      "reason": "The psychological suspense and dark atmosphere echo the noir qualities they loved in Sunset Boulevard and Touch of Evil."
    }
  ]
}

Parsed recommendations:
  • The Conversation                    predicted=4.3  — This psychological thriller shares the dark, suspenseful qualities of Touch of Evil and the serious dramatic weight of Sunset Boulevard.
  • Psycho                              predicted=4.2  — The psychological thriller elements and dark tone align perfectly with their love for Touch of Evil and Sunset Boulevard's noir sensibilities.
  • To Kill a Mockingbird               predicted=4.1  — This serious courtroom drama matches their appreciation for weighty dramatic material like Cat on a Hot Tin Roof and The Shawshank Redemption.
  • Casino                              predicted=4.0  — The dark crime epic tone resonates with their high ratings for Touch of Evil and The Shawshank Redemption's criminal underworld elements.
  • Rosemary's Baby                     predicted=3.9  — The psychological suspense and dark atmosphere echo the noir qualities they loved in Sunset Boulevard and Touch of Evil.

In [27]:
# Deterministic split
all_rows = pd.read_sql(
    """SELECT title, genres, sub_genre, tone, sentiment, target_audience,
               budget_tier, revenue_tier, runtime, avg_rating
       FROM enriched_movies
       WHERE avg_rating IS NOT NULL
       ORDER BY title""", conn)
random.seed(42)
indices = list(range(len(all_rows)))
random.shuffle(indices)
HOLDOUT = all_rows.iloc[indices[:5]].reset_index(drop=True)
FEWSHOT = all_rows.iloc[indices[5:13]].reset_index(drop=True)

print("Few-shot exemplars (8):")
print(FEWSHOT[["title", "genres", "tone", "avg_rating"]].to_string(index=False))
print("\nHold-out (5) — ground truth hidden from the model:")
print(HOLDOUT[["title", "genres", "tone"]].to_string(index=False))
print("\nGround truth (for evaluation only):")
print(HOLDOUT[["title", "avg_rating"]].to_string(index=False))

Few-shot exemplars (8):
                          title                          genres        tone  avg_rating
              Dial M for Murder          Crime|Mystery|Thriller suspenseful       3.600
   20,000 Leagues Under the Sea Adventure|Drama|Science Fiction suspenseful       2.564
                   Spider-Man 2        Action|Adventure|Fantasy     serious       2.667
                     Blind Date                  Comedy|Romance    humorous       3.571
                  Roman Holiday                  Comedy|Romance    romantic       2.893
                  Secret Window                Thriller|Mystery suspenseful       2.759
                    Angel Heart         Horror|Mystery|Thriller        dark       3.857
One Flew Over the Cuckoo's Nest                           Drama     serious       2.300

Hold-out (5) — ground truth hidden from the model:
               title                     genres          tone
  The Out-of-Towners                     Comedy      humorous
               Rocky                      Drama inspirational
             Sabrina       Comedy|Drama|Romance      romantic
An American in Paris Drama|Comedy|Music|Romance  lighthearted
    Fantastic Voyage  Adventure|Science Fiction   suspenseful

Ground truth (for evaluation only):
               title  avg_rating
  The Out-of-Towners       3.851
               Rocky       3.962
             Sabrina       3.647
An American in Paris       2.333
    Fantastic Voyage       3.303

In [28]:
# Build the few-shot prompt
def fmt_movie_features(r):
    return (f"genres={r['genres']} | sub_genre={r['sub_genre']} | tone={r['tone']} | "
            f"sentiment={r['sentiment']} | audience={r['target_audience']} | "
            f"budget_tier={r['budget_tier']} | revenue_tier={r['revenue_tier']} | "
            f"runtime={r['runtime']}min")

PRED_SYSTEM = textwrap.dedent("""\
    You predict average user ratings on a 0.5-5.0 scale (typical real-world
    range is 2.0-4.5) for movies based on their features. Output ONE number
    rounded to 3 decimals, nothing else.
""")

def build_pred_prompt(target_features: str) -> str:
    parts = ["Examples:"]
    for _, r in FEWSHOT.iterrows():
        parts.append(f"Movie: {r['title']}\nFeatures: {fmt_movie_features(r)}\nRating: {r['avg_rating']:.3f}")
    parts.append(f"\nMovie: <held out>\nFeatures: {target_features}\nRating:")
    return "\n\n".join(parts)

predictions = []
for _, r in HOLDOUT.iterrows():
    feats = fmt_movie_features(r)
    raw = call_llm(build_pred_prompt(feats), system=PRED_SYSTEM, max_tokens=20).strip()
    try:
        pred = float(re.findall(r"-?\d+\.?\d*", raw)[0])
    except (IndexError, ValueError):
        pred = float("nan")
    predictions.append((r["title"], r["avg_rating"], pred))
    print(f"  {r['title']:<40}  truth={r['avg_rating']:.3f}  pred={pred}")

import math
errors = [abs(t - p) for _, t, p in predictions if not math.isnan(p)]
print(f"\nMAE over {len(errors)} predictions: {sum(errors)/len(errors):.3f}")
print("\n[CAVEAT] N=5 hold-out from a 96-movie DB. This MAE is illustrative, not a benchmark.")

/var/folders/m8/30j490cd23vdfw3yn93z97tm0000gn/T/ipykernel_37720/2853460120.py:28: DeprecationWarning: The model 'claude-sonnet-4-20250514' is deprecated and will reach end-of-life on June 15th, 2026.
Please migrate to a newer model. Visit https://docs.anthropic.com/en/docs/resources/model-deprecations for more information.
  resp = _get_client().messages.create(**kwargs)

  The Out-of-Towners                        truth=3.851  pred=3.214

/var/folders/m8/30j490cd23vdfw3yn93z97tm0000gn/T/ipykernel_37720/2853460120.py:28: DeprecationWarning: The model 'claude-sonnet-4-20250514' is deprecated and will reach end-of-life on June 15th, 2026.
Please migrate to a newer model. Visit https://docs.anthropic.com/en/docs/resources/model-deprecations for more information.
  resp = _get_client().messages.create(**kwargs)

  Rocky                                     truth=3.962  pred=3.125

/var/folders/m8/30j490cd23vdfw3yn93z97tm0000gn/T/ipykernel_37720/2853460120.py:28: DeprecationWarning: The model 'claude-sonnet-4-20250514' is deprecated and will reach end-of-life on June 15th, 2026.
Please migrate to a newer model. Visit https://docs.anthropic.com/en/docs/resources/model-deprecations for more information.
  resp = _get_client().messages.create(**kwargs)

  Sabrina                                   truth=3.647  pred=3.214

/var/folders/m8/30j490cd23vdfw3yn93z97tm0000gn/T/ipykernel_37720/2853460120.py:28: DeprecationWarning: The model 'claude-sonnet-4-20250514' is deprecated and will reach end-of-life on June 15th, 2026.
Please migrate to a newer model. Visit https://docs.anthropic.com/en/docs/resources/model-deprecations for more information.
  resp = _get_client().messages.create(**kwargs)

  An American in Paris                      truth=2.333  pred=3.214

/var/folders/m8/30j490cd23vdfw3yn93z97tm0000gn/T/ipykernel_37720/2853460120.py:28: DeprecationWarning: The model 'claude-sonnet-4-20250514' is deprecated and will reach end-of-life on June 15th, 2026.
Please migrate to a newer model. Visit https://docs.anthropic.com/en/docs/resources/model-deprecations for more information.
  resp = _get_client().messages.create(**kwargs)

  Fantastic Voyage                          truth=3.303  pred=nan

MAE over 4 predictions: 0.697

[CAVEAT] N=5 hold-out from a 96-movie DB. This MAE is illustrative, not a benchmark.

In [29]:
# Two contrasting movies — high-budget recent franchise vs. classic low-budget icon
COMPARE = pd.read_sql(
    """SELECT title, releaseDate, budget, revenue, runtime, avg_rating,
              sentiment, tone, genres, production_effectiveness_score
       FROM enriched_movies
       WHERE title IN ('Spider-Man 2', 'Sunset Boulevard')
       ORDER BY budget DESC""", conn)
print(COMPARE.to_string(index=False))

           title releaseDate    budget   revenue  runtime  avg_rating sentiment    tone                   genres  production_effectiveness_score
    Spider-Man 2  2004-06-25 200000000 783766341    127.0       2.667   neutral serious Action|Adventure|Fantasy                           0.389
Sunset Boulevard  1950-08-10   1752000   5000000    110.0       4.036  negative    dark                    Drama                           0.507

In [31]:
COMPARE_SYSTEM = textwrap.dedent("""\
    You are a film analyst. Compare two movies on quantitative and qualitative
    dimensions. Think step-by-step in the `reasoning` field, then give a concise
    `verdict`. Output STRICT JSON only:

    {
      "reasoning": {
        "budget":   "<comparison + what it implies>",
        "revenue":  "<comparison + ROI implications>",
        "runtime":  "<comparison>",
        "sentiment_and_tone": "<comparison>",
        "rating":   "<comparison + what audiences seem to value>"
      },
      "verdict": "<2-3 sentences: which film 'wins' on which axis, and why a viewer might prefer each>"
    }
""")

def fmt_movie_compare(r):
    return (f"{r['title']} ({r['releaseDate']}): "
            f"budget=${r['budget']:,} | revenue=${r['revenue']:,} | "
            f"runtime={r['runtime']} | avg_rating={r['avg_rating']} | "
            f"sentiment={r['sentiment']} | tone={r['tone']} | "
            f"genres={r['genres']} | prod_eff={r['production_effectiveness_score']}")

prompt = "Compare these two movies:\n\n" + "\n".join(fmt_movie_compare(r) for _, r in COMPARE.iterrows())
raw = call_llm(prompt, system=COMPARE_SYSTEM, max_tokens=900, prefill="{")
print(raw)
parsed = json.loads(raw)
print("\n=== VERDICT ===")
print(parsed["verdict"])

/var/folders/m8/30j490cd23vdfw3yn93z97tm0000gn/T/ipykernel_37720/2853460120.py:28: DeprecationWarning: The model 'claude-sonnet-4-20250514' is deprecated and will reach end-of-life on June 15th, 2026.
Please migrate to a newer model. Visit https://docs.anthropic.com/en/docs/resources/model-deprecations for more information.
  resp = _get_client().messages.create(**kwargs)

{
  "reasoning": {
    "budget": "Spider-Man 2 had a massive $200M budget vs Sunset Boulevard's $1.75M (adjusted for inflation, still a huge gap). This reflects the evolution from character-driven drama to effects-heavy blockbuster filmmaking, with Spider-Man 2 requiring extensive CGI and action sequences.",
    "revenue": "Spider-Man 2 grossed $783M globally vs Sunset Boulevard's $5M, but ROI tells a different story - Spider-Man 2 made 3.9x its budget while Sunset Boulevard made 2.9x. Spider-Man 2's higher absolute revenue reflects modern global distribution and higher ticket prices.",
    "runtime": "Spider-Man 2 runs 17 minutes longer (127 vs 110 minutes), typical of modern blockbusters that pack in more action sequences and subplots compared to the tighter pacing of classic Hollywood films.",
    "sentiment_and_tone": "Stark contrast - Spider-Man 2 maintains neutral sentiment with serious tone (heroic journey with personal struggles), while Sunset Boulevard is deeply negative and dark, exploring Hollywood's destructive nature and delusion. This reflects their different narrative purposes.",
    "rating": "Sunset Boulevard significantly outperforms with 4.036 vs 2.667 average rating, suggesting audiences and critics value its artistic merit, complex themes, and timeless commentary over Spider-Man 2's entertainment value, despite the latter's commercial success."
  },
  "verdict": "Sunset Boulevard wins on artistic merit and critical acclaim, offering a psychologically complex, enduring masterpiece that critiques Hollywood itself. Spider-Man 2 dominates commercially and delivers spectacular entertainment value with impressive production efficiency for a modern blockbuster. Viewers seeking profound drama and film history should choose Sunset Boulevard, while those wanting thrilling superhero action and visual spectacle should pick Spider-Man 2."
}

=== VERDICT ===
Sunset Boulevard wins on artistic merit and critical acclaim, offering a psychologically complex, enduring masterpiece that critiques Hollywood itself. Spider-Man 2 dominates commercially and delivers spectacular entertainment value with impressive production efficiency for a modern blockbuster. Viewers seeking profound drama and film history should choose Sunset Boulevard, while those wanting thrilling superhero action and visual spectacle should pick Spider-Man 2.

In [32]:
SUMMARY_SYSTEM = textwrap.dedent("""\
    You write concise (4-6 sentences) movie taste summaries for a user given
    their rating history. Reference specific movies they rated highly. Mention
    tone, era, and themes. Plain prose, no headers, no JSON.
""")

uid = "u2_popcorn_action"
u = USERS[uid]
lines = [f"User watched and rated:"]
for t, r in u["ratings"]:
    meta = pd.read_sql("SELECT genres, sub_genre, tone FROM enriched_movies WHERE title = ?", conn, params=[t]).iloc[0]
    lines.append(f"  - {t} (rated {r}/5) — {meta['genres']} | {meta['sub_genre']} | {meta['tone']}")
prompt = "\n".join(lines) + "\n\nWrite their taste summary."
print(call_llm(prompt, system=SUMMARY_SYSTEM, max_tokens=400))

/var/folders/m8/30j490cd23vdfw3yn93z97tm0000gn/T/ipykernel_37720/2853460120.py:28: DeprecationWarning: The model 'claude-sonnet-4-20250514' is deprecated and will reach end-of-life on June 15th, 2026.
Please migrate to a newer model. Visit https://docs.anthropic.com/en/docs/resources/model-deprecations for more information.
  resp = _get_client().messages.create(**kwargs)

This viewer gravitates toward expertly crafted action films that balance spectacle with strong storytelling, particularly favoring the adventure-driven thrills of Indiana Jones and the Last Crusade and the emotionally grounded superhero drama of Spider-Man 2. They appreciate both lighthearted adventure romps and more serious, suspenseful fare like The Bourne Supremacy, suggesting a taste for well-executed genre filmmaking across different tones. Their ratings indicate a preference for films that deliver on their genre promises with solid craftsmanship, whether it's classic adventure serials, modern spy thrillers, or character-driven action dramas. While they can enjoy family-friendly content like Mary Poppins, their highest ratings go to films that combine exciting action sequences with compelling characters and stakes that feel genuinely meaningful.